// Turns src/design-tools.css into a plain TypeScript module holding the stylesheet as a
// string, so the component can inject its own styles at runtime.
//
// The alternative — `import './design-tools.css'` inside the component — only works when the
// consumer's bundler is configured to handle CSS imports. It throws outright under plain Node
// (SSR, Jest, any non-bundled import), which made the package unusable in those environments.
// Generating a .ts module keeps the styles bundler-agnostic and zero-config for consumers.
//
// Runs before tsc; the generated file is git-ignored and regenerated on every build.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const css = readFileSync(join(root, 'src', 'design-tools.css'), 'utf8');
const out = join(root, 'src', 'generated', 'designToolsCss.ts');

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-styles.mjs — do not edit. Edit src/design-tools.css instead.\n` +
    `export const designToolsCss = ${JSON.stringify(css)};\n`,
  'utf8',
);
console.log('generated src/generated/designToolsCss.ts');
